version: '3'

services:
  go:
    container_name: api-server2
    platform: linux/x86_64
    hostname: localhost
    tty: true
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./back:/go/src/app